---
services:
  crauto-app-jenkins-controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: mohamedhamdyamer/crauto-app-jenkins-controller:latest
    container_name: crauto-app-jenkins-controller
    hostname: crauto-app-jenkins-controller
    restart: on-failure
    environment:
      - Jenkins_URL=
      - Docker_Host_URI=
      - Dockerized_Jenkins_Agent_Image_Name=mohamedhamdyamer/crauto-app-jenkins-agent:latest
      - Repo_URL=https://github.com/mohamedhamdyamer/crauto
    ports:
      - "8080:8080"
      - "50000:50000"
